# This is a default home.nix generated by the following home-manager command
#
# home-manager init ./
{
  lib,
  pkgs,
  ...
}: {
  godtamnix = {
    user = {
      enable = true;
      name = "godtamit";
      fullName = "Christopher Tam";
      email = lib.godtamnix.decode "b2hnb2R0YW1pdEBnbWFpbC5jb20=";
    };

    programs.graphical.browsers = {
      firefox = {
        enable = true;
        # gpuAcceleration = true;
        # hardwareDecoding = true;
        # setDefault = true;
      };
    };
  };

  home.packages = with pkgs; [
    discord
    ferdium
    neofetch
    signal-desktop
    unzrip
    webull-desktop
  ];

  programs = {
    fish = {
      enable = true;

      loginShellInit = ''
        set -x NIX_PATH nixpkgs=channel:nixos-unstable
        set -x NIX_LOG info
        set -x TERMINAL kitty
      '';

      interactiveShellInit = ''
        set -x fish_greeting # This sets the greeting to nothing
        neofetch
      '';

      shellAbbrs = {
        ".." = "cd ..";
        "..." = "cd ../..";
        ag = "antigravity";
        ls = "eza";
        grep = "rg";
        ps = "procs";
        unzip = "unzrip";

        # k8s aliases
        k = "kubectl";
        kctx = "kubectx";
        kns = "kubens";

        # Git aliases
        gbrclean = "git fetch -p && for branch in $(git branch -vv | grep ': gone]' | awk '{print $1}'); git branch -D $branch; end";
        gbrls = "git branch -v";
        gfp = "git fetch --prune";
        gco = "git checkout";
        gcoom = "git commit";
        gcoom-a = "git commit --amend";
        gcoom-ane = "git commit --amend --no-edit";
        gpsh = "git push";
        gpshfwl = "git push --force-with-lease";
        gpff = "git pull --ff-only";
        gst = "git status";
        gunstage = "git restore --staged";
      };
    };

    git = {
      enable = true;

      settings = {
        push.autoSetupRemote = true;
      };
    };

    ssh = {
      enable = true;
      enableDefaultConfig = false;

      matchBlocks = {
        "BeastieServerV2" = {
          hostname = lib.godtamnix.decode "YmVhc3RpZXNlcnZlcnYyLmdvZHRhbWl0LmNvbQ==";
          user = "godtamit";
          port = 38888;
        };
      };
    };

    starship = {
      enable = true;

      enableFishIntegration = true;
      enableInteractive = true;

      settings = fromTOML (builtins.readFile ./starship.toml);
    };

    trippy = {
      enable = true;
    };

    yazi = {
      enable = true;

      enableFishIntegration = true;
    };
  };

  xdg.configFile."Antigravity/Users/settings.json".source = ./antigravity-settings.json;
}
