# This is a default home.nix generated by the following home-manager command
#
# home-manager init ./
{
  lib,
  pkgs,
  ...
}: {
  godtamnix = {
    user = {
      enable = true;
      name = "godtamit";
      fullName = "Christopher Tam";
      email = lib.godtamnix.decode "b2hnb2R0YW1pdEBnbWFpbC5jb20=";
    };

    programs.graphical.browsers = {
      firefox = {
        enable = true;
        # gpuAcceleration = true;
        # hardwareDecoding = true;
        # setDefault = true;
      };
    };

    programs.terminal.ai.opencode = {
      settings = builtins.fromJSON (builtins.readFile ./opencode.json);
      # ohMyOpenAgent = builtins.fromJSON (builtins.readFile ./oh-my-openagent.json);
      ohMyOpenCodeSlim = builtins.fromJSON (builtins.readFile ./oh-my-opencode-slim.json);
    };
  };

  home.packages = with pkgs;
    [
      bitwarden-desktop
      discord
      fastfetch
      signal-desktop
      unzrip
    ]
    ++ lib.optionals pkgs.stdenv.hostPlatform.isLinux [
      ferdium
      webull-desktop
    ]
    ++ lib.optionals pkgs.stdenv.hostPlatform.isDarwin [
      scroll-reverser
    ];

  programs = {
    claude-code = {
      enable = true;
    };

    fish = {
      enable = true;

      loginShellInit = ''
        set -x NIX_PATH nixpkgs=channel:nixos-unstable
        set -x NIX_LOG info
        set -x TERMINAL kitty
      '';

      interactiveShellInit = ''
        set -x fish_greeting # This sets the greeting to nothing
        fastfetch
      '';

      shellAbbrs = {
        ".." = "cd ..";
        "..." = "cd ../..";
        ag = "antigravity";
        ls = "eza";
        grep = "rg";
        ps = "procs";
        unzip = "unzrip";

        # k8s aliases
        k = "kubectl";
        kctx = "kubectx";
        kns = "kubens";

        # Git aliases
        gbrclean = "git fetch -p && for branch in $(git branch -vv | grep ': gone]' | awk '{print $1}'); git branch -D $branch; end";
        gbrls = "git branch -v";
        gfp = "git fetch --prune";
        gco = "git checkout";
        gcoom = "git commit";
        gcoom-a = "git commit --amend";
        gcoom-ane = "git commit --amend --no-edit";
        gpsh = "git push";
        gpshfwl = "git push --force-with-lease";
        gpff = "git pull --ff-only";
        gst = "git status";
        gunstage = "git restore --staged";
        gwt = "git worktree";
        gwtrm = "git worktree remove";
        gwtrmf = "git worktree remove -f";
        gwtkill = "git kill-tree";
      };
    };

    git = {
      enable = true;

      settings = {
        push.autoSetupRemote = true;

        alias = {
          kill-tree = "!f() { if git show-ref --verify --quiet refs/heads/\"$1\"; then git worktree remove -f \"$1\" && git branch -D \"$1\"; else echo \"Branch $1 not found\"; fi; }; f";
        };
      };
    };

    ssh = {
      enable = true;
      enableDefaultConfig = false;

      settings = {
        "BeastieServerV2" = {
          HostName = lib.godtamnix.decode "YmVhc3RpZXNlcnZlcnYyLmdvZHRhbWl0LmNvbQ==";
          User = "godtamit";
          Port = 38888;
        };

        "IceCube" = {
          HostName = lib.godtamnix.decode "aWNlY3ViZS5nb2R0YW1pdC5jb20=";
          User = "godtamit";
          Port = 48888;
        };

        "shaq" = {
          HostName = lib.godtamnix.decode "c2hhcS5kZXYuYXN0LmxpdmU=";
          User = "godtamit";
          Port = 38888;
        };
      };
    };

    starship = {
      enable = true;

      enableFishIntegration = true;
      enableInteractive = true;

      settings = fromTOML (builtins.readFile ./starship.toml);
    };

    trippy = {
      enable = true;
    };

    yazi = {
      enable = true;
      enableFishIntegration = true;
      shellWrapperName = "y";
    };

    zed-editor = {
      enable = true;

      # This populates the userSettings "auto_install_extensions"
      extensions = ["nix" "toml" "make" "catppuccin" "svelte" "graphql"];

      # Everything inside of these brackets are Zed options
      userSettings = builtins.fromJSON (builtins.readFile ./zed-settings.json);
    };
  };

  xdg.configFile."Antigravity/User/settings.json".source = ./antigravity-settings.json;
}
