# This is a default home.nix generated by the follwing hone-manager command
#
# home-manager init ./
{
  lib,
  pkgs,
  ...
}:
let
  ff-lock-false = {
    Value = false;
    Status = "locked";
  };
  ff-lock-true = {
    Value = true;
    Status = "locked";
  };
in
{
  godtamnix = {
    user = {
      enable = true;
      name = "godtamit";
      fullName = "Christopher Tam";
      email = lib.godtamnix.decode "b2hnb2R0YW1pdEBnbWFpbC5jb20=";
    };
  };

  home.packages = with pkgs; [
    antigravity
    brave
    discord
    plex-desktop

    # Fonts
    fira-code
    fira-code-symbols
    font-awesome
    font-manager
    nerd-fonts.fira-code
    noto-fonts
  ];

  programs = {
    firefox = {
      enable = true;
      languagePacks = [ "en-US" ];

      # ---- POLICIES ----
      # Check about:policies#documentation for options.
      policies = {
        DisableTelemetry = true;
        DisableFirefoxStudies = true;
        EnableTrackingProtection = {
          Value = true;
          Locked = true;
          Cryptomining = true;
          Fingerprinting = true;
        };
        DisablePocket = true;
        # DisableFirefoxAccounts = true;
        # DisableAccounts = true;
        # DisableFirefoxScreenshots = true;
        OverrideFirstRunPage = "";
        OverridePostUpdatePage = "";
        DontCheckDefaultBrowser = true;
        DisplayBookmarksToolbar = "never"; # alternatives: "always" or "newtab"
        DisplayMenuBar = "default-off"; # alternatives: "always", "never" or "default-on"
        SearchBar = "unified"; # alternative: "separate"

        # ---- EXTENSIONS ----
        # Check about:support for extension/add-on ID strings.
        # Valid strings for installation_mode are "allowed", "blocked",
        # "force_installed" and "normal_installed".
        ExtensionSettings = {
          # "*".installation_mode = "blocked"; # blocks all addons except the ones specified below
          # uBlock Origin:
          "uBlock0@raymondhill.net" = {
            install_url = "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi";
            installation_mode = "force_installed";
          };
          # Privacy Badger:
          "jid1-MnnxcxisBPnSXQ@jetpack" = {
            install_url = "https://addons.mozilla.org/firefox/downloads/latest/privacy-badger17/latest.xpi";
            installation_mode = "force_installed";
          };
          # Bitwarden:
          "{446900e4-71c2-419f-a6a7-df9c091e268b}" = {
            install_url = "https://addons.mozilla.org/firefox/downloads/latest/bitwarden-password-manager/latest.xpi";
            installation_mode = "force_installed";
          };
          # Return YouTube Dislikes:
          "{762f9885-5a13-4abd-9c77-433dcd38b8fd}" = {
            install_url = "https://addons.mozilla.org/firefox/downloads/latest/return-youtube-dislikes/latest.xpi";
            installation_mode = "force_installed";
          };
          # Tree Style Tab
          "treestyletab@piro.sakura.ne.jp" = {
            install_url = "https://addons.mozilla.org/firefox/downloads/latest/tree-style-tab/latest.xpi";
            installation_mode = "force_installed";
          };
          # TST Colored Tabs
          "tst-colored-tabs@murz" = {
            install_url = "https://addons.mozilla.org/firefox/downloads/latest/tst-colored-tabs/latest.xpi";
            installation_mode = "force_installed";
          };
          # Cookie Quick Manager
          "{60f82f00-9ad5-4de5-b31c-b16a47c51558}" = {
            install_url = "https://addons.mozilla.org/firefox/downloads/latest/cookie-quick-manager/latest.xpi";
            installation_mode = "force_installed";
          };
          # Firefox Multi-Account Containers
          "@testpilot-containers" = {
            install_url = "https://addons.mozilla.org/firefox/downloads/latest/multi-account-containers/latest.xpi";
            installation_mode = "force_installed";
          };
          # Facebook Container
          "@contain-facebook" = {
            install_url = "https://addons.mozilla.org/firefox/downloads/latest/facebook-container/latest.xpi";
            installation_mode = "force_installed";
          };
          # MetaMask
          "webextension@metamask.io" = {
            install_url = "https://addons.mozilla.org/firefox/downloads/latest/ether-metamask/latest.xpi";
            installation_mode = "force_installed";
          };
        };

        # ---- PREFERENCES ----
        # Check about:config for options.
        Preferences = {
          # "browser.contentblocking.category" = { Value = "strict"; Status = "locked"; };
          "extensions.pocket.enabled" = ff-lock-false;
          "extensions.screenshots.disabled" = ff-lock-true;
          "browser.topsites.contile.enabled" = ff-lock-false;
          "browser.formfill.enable" = ff-lock-false;
          "browser.search.suggest.enabled" = ff-lock-false;
          "browser.search.suggest.enabled.private" = ff-lock-false;
          # "browser.urlbar.suggest.searches" = ff-lock-false;
          "browser.urlbar.showSearchSuggestionsFirst" = ff-lock-false;
          "browser.newtabpage.activity-stream.feeds.section.topstories" = ff-lock-false;
          "browser.newtabpage.activity-stream.feeds.snippets" = ff-lock-false;
          "browser.newtabpage.activity-stream.section.highlights.includePocket" = ff-lock-false;
          "browser.newtabpage.activity-stream.section.highlights.includeBookmarks" = ff-lock-false;
          "browser.newtabpage.activity-stream.section.highlights.includeDownloads" = ff-lock-false;
          "browser.newtabpage.activity-stream.section.highlights.includeVisited" = ff-lock-false;
          "browser.newtabpage.activity-stream.showSponsored" = ff-lock-false;
          "browser.newtabpage.activity-stream.system.showSponsored" = ff-lock-false;
          "browser.newtabpage.activity-stream.showSponsoredTopSites" = ff-lock-false;
        };
      };
    };

    fish = {
      enable = true;

      loginShellInit = ''
        set -x NIX_PATH nixpkgs=channel:nixos-unstable
        set -x NIX_LOG info
        set -x TERMINAL kitty

        if test (tty) = "/dev/tty1"
          exec Hyprland &> /dev/null
        end
      '';

      shellAbbrs = {
        ".." = "cd ..";
        "..." = "cd ../..";
        ls = "eza";
        grep = "rg";
        ps = "procs";

        # Git aliases
        gco = "git checkout";
        gcoom = "git commit";
        gcoom-a = "git commit --amend";
        gcoom-ane = "git commit --amend --no-edit";
        gpsh = "git push";
        gpshfwl = "git push --force-with-lease";
        gpff = "git pull --ff-only";
        gst = "git status";
      };
    };
  };
}
