cloudflare_api_token: ENC[AES256_GCM,data:watkHPdHRj/ZWHWRWuv3V5Q4zaaJIi4xj1iNcoz6Qq/GdEzxmYEwKRU8d48smwCltcR1iis=,iv:pBB89RjR9ZOhD7+2gl+jva37TDmHzP5QGztCMtG2nQM=,tag:52ZKZ96qx8s/hcEu3DsrQA==,type:str]
cloudflare_acme_credentials: ENC[AES256_GCM,data:4MHysVP8GCrDGNvFmMZHiMgxM8TmxOLQpL1GP30Ddh2Kxbq224lzmeSrrN+Ak2pItb4XaTLDlZmzYuKa01FH,iv:KuCEjrfYmTodEw1gnB/w56vlr6NSeM5xtUcm9KtcwRg=,tag:PJpoQhqKjmF/T1mYfJJE9Q==,type:str]
sops:
  age:
    - recipient: age1gmxyeqces6e0t2d5v5lcplm7e4fkw64w4yvfcjz2ca4ee2k43v5smre7z9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK0dqYWVwSlF6UFNMcFgw
        dGNxeGVlZFNVRDJscGZzelh3dktTZHVkOTAwCkk4ZVcvcFZhVmk5QWpIR2VRNmNU
        VnhmN3hMemF2NC9HUTVaelVVNk9SL2MKLS0tIHR5NDhRV3hFaE1IM2FMWHVDWUZW
        REE0YlFPcnlRSEVpeG9namtjU3FIak0KYvebPZwr5wD2+6XxyaH0ASv/uUJ0ptKZ
        dqAI9dMGwTuuF5FoO+8xv6wp8lmuGJT2n6t23P+DT6TbTNJODYbZTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-04T20:18:59Z"
  mac: ENC[AES256_GCM,data:GaQartfCF4OV8nX3x349XaYHHuVc3nMYYMHxfioTafMx/VzhHmnkg1VG/AtzoCKNSGOmVKZao9zaI3xIuA6Exiy+vKWu8BxYxv+a16R7IKzbMkCYwfsiD+DV82h7HbyvCUgJv2NGGoNkmXiBp3aF9JwIRIPOb8eAUm5Yhj+hHCk=,iv:oMsRkCjSl0fj/BkJ+aXNsj/Ickyg+rW/h5XKl790eMg=,tag:j+LGcbqEybz0kyqUzol7eg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
