cloudflare_api_token: ENC[AES256_GCM,data:y27SlAjkbzPQ6EEMEDVxao1r5b1RpRB4qPLKYbF0+JDeMe6t5GztII48kCGynDCcwkwEyfY=,iv:69X1lFmbCsyWxQ7ZqHOeocVU97+5f33bMoDYGWG79HY=,tag:q1F5FqT6Gt5cNcsErLSpLQ==,type:str]
cloudflare_acme_credentials: ENC[AES256_GCM,data:r63iPSxBnL/WuN8YAbsxGF4vXL2Xu22Ywo2ZbaMuoh/Fok322cHshaZ+leyTvmRYBzW6l1fi21PGLLtAprCu,iv:FWcZoj4PdsYeHKyR4VO7UjhgOuG+RO8YDryyB0H8UvE=,tag:GoSmo0hE0U82uIHQb3d4Ng==,type:str]
sops:
  age:
    - recipient: age1gmxyeqces6e0t2d5v5lcplm7e4fkw64w4yvfcjz2ca4ee2k43v5smre7z9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRWhpbXZ6aFlyWjdQMnBR
        Qmk0eE1VVGFmcjFWTGFvNGI5YXd4YjJaSjNFCkc4MHR2cXRZQ1FYb0oyeEN4MTZC
        UjRDS0RranBMVW1WMUdPV0Mwa3I0NG8KLS0tIEJGUTQrUkZXeUpkb3pPajQ5TWZN
        akxKbzRtcSsvVVRYSUtZUHhrTTJOaHcKNMXloVOp9Z0IX4Tm5eBvRh/j9dHh0RRB
        1vjX2ln2SSd/T8xhHwI/Wjw9hxjO0m4Y6kJ9/9ShxYeJSwYgr4lRYw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1lzp44tfsadmsp669u4e6ma9dlj3wwms44f7ydhmzlm9tvfpjv30ssjm2rj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXT0liTzBncDYrWjJqQjFq
        Mk52NGFQNWdWTCtZWmFKSDYxZXZFMW54dWdnCmFKZkx3RzlRWGVzaVZTZ1pibnpr
        V3pmWXRWSlREaG5ReHk3OWwrNEhwcDQKLS0tIE43TVA3Q2hLUmhwc0htZVlUWTE0
        cTJRL095YWN3OHNpQTFhSG02TW1YR00KhuYdKVNBYjTptw2WfoTPiWVCXyS+/LGo
        eXVmZFw4ML5tKYtMPUSrRjbEzABRryvMJTuz42j/Ee/SOXaY0wE/UA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1hcrm3rwpal3pgvekcluysya6ezyymn84f7r9382jyedprj9geymscya522
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMW0raGxKYVBnR0RuSFF5
        WmVWbVMzTTJ5ZUxkbFdMenFmQmE3UkZvd2owCi8xSkR5VlZSNll5RHZFK3JvckNs
        eHI3enBiUW9iVjZOSmVqSW9UQ2MxaHMKLS0tIHA0Z2VibXQ3SzNhcTlScWJ2NkVv
        Z2o0L2p6UFRhMU9reFNabXZmdy9TQUUKOss0adl1jf+dtJXXkCExhwWmme9C7sZ+
        oIOcNbjoD4GhgbaWgOfaAGtESqC76hNO/tTJHuTGInfg6yp2TCU1+g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-05T03:55:23Z"
  mac: ENC[AES256_GCM,data:83oohTJVD6ktKmV8iEEzHH+EcbSk1viD5vzF5bfFNK5CdcP0eMAWsxQYf1PfZxrkwsqyBvQP44ZxTe3lUsh8V9CmTeOWcpVcXhHG7Eo1KIKm6+W0pQ+S8CT810j8mpKf6gB6O1Dx9fLhwy4k9MuNeNAc1jH13xJVWVOe9Pschsk=,iv:Oh4GKlRiLK4kkaeNAzN5V6RaqWLac02kd0JpPyaQPjw=,tag:lmK+bMMfmcZxcMU4ZK5Org==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
