cloudflare_api_token: ENC[AES256_GCM,data:w9I6opW2/GHpxJdah5VW8XW5JsQA3kjRj1Yc0LmqR/jqX+PZm2ZjbZpGV7wIPoeSo5Iy/gM=,iv:ujoAuulwAsvcbHkX7YAzZx5siKjGQp2LsF21i53kqmE=,tag:o+icwkpieh4s8agTYvBCbQ==,type:str]
sops:
  age:
    - recipient: age1qfyt67lmzynymvstl0e7l0sstgh2wev6htt34s2lphapzsdr246s5txqm8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUlU2VWtXK05UNjNXTjhE
        M3MvRytlS1JNOGNQd1dBc0RjQ28zcUFmY1ZJClY5WHhaUWRFK2ZjdU02V3hERm9N
        RmdIMHpFM2hPdjA5dXo3UDFHcnRVMHMKLS0tIHFpMEk1ek5zQ1lER2tYYmZyZExD
        c3JNdjd0VE9ORWNBSy9yMUZUdHF1RUUKu+h/9qtI+1XF3QJZRk7K0Uw9JanDjJnc
        KNMp94PuYDOPee6mjJ7RJBGxbcjLr7etjFrdMT/qUk9026UMb19F5w==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1gmxyeqces6e0t2d5v5lcplm7e4fkw64w4yvfcjz2ca4ee2k43v5smre7z9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTHVEWEttSTFKbWY1Vzdh
        N0t6YTNybDhTT2VEN29xcVpIa2V4U2p2L0U4CnZxeXpjL3REQ01xWnhHVDIvZTJQ
        b0dMSnZ5WmhoQUwrVzZXaVBDcnJmcHcKLS0tIHFRQzhFZVh1NHViOGVHV2FkcVA1
        TEF5eE9CUTJubjJWMHJtM1laUHg1UnMKLv/T27n0rQqGTfH6AFmpQGRKsapOhJYo
        f3vim3khfCjdkqAQxpQANLgPMw73pVvY2ut9i11bERvpg8MpCrWKyg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-28T01:18:06Z"
  mac: ENC[AES256_GCM,data:e9fZkugjOUpTrYZEoA5dXDfLOFKlLyOeotq6/0SMOvpM2/UwQMdhZeTXpX3s5nbR3OOdZeta+pEbUr2nFktwOIvlKMRkS7Gr9EhEeakKn2V1g45afr24XZzy5AV35VY3Kq5SxUlHSWkmdJpVps2edTzc+DMYy1Gi2V8qm2x+ns4=,iv:/twXBSzuf2A9Wf6tpxeRGRjwocSctMldtgoppsvrWLw=,tag:aC2+zXW5KT5NWMD6pzV7zg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
