cloudflare_api_token: ENC[AES256_GCM,data:9OX7FkfCkSx9j1OXEkPSOMPsGtKLjekkOjKDXNur30KB6VtlnPdWNDp0GwPadeoiQKB8D6I=,iv:s0KEspJDypjYiYdOEANtWnpbDA6KMcMjfYWL3qWESOo=,tag:1WKyarSSIV8EHSXyDO6Xsg==,type:str]
sops:
    age:
        - recipient: age1dsq3jfksmka0gdkxpqpfglyvcusutspj007y4yzsmwfyfyp92yusy7wnlg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU1kxUmVrU1V4eWxzRlpD
            VFNNQlhQV3lWMkFCbEFYWGt5VlhZSk5sMndvCkl0TVFSUi9ST29NTDBpYXcwZVRD
            MG91S3ZTUGRlazlZL2JmOG1Xc1lHRDAKLS0tIDR3dEZJc0JUM1k4V0FUL0ptODg5
            c3FzaU5XcXo5dWY1T2owRFpQUXZqOXcKLqROQz1s2qDIX6sUEtYxbwixN32uYyfy
            M6kTsQeGN0koniz0NyuXFBFrVT6idTzhgfXLBFN0XKToUM47NCuUjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1c3jfx5pxy0ttfxwkwp9cmrclg0en4t04j09342ed622pc5kal9essafrhp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsLzNaT3FwUFc5clhvSG1W
            dm03SW0wOGt3bjBDcVJCWW96eGZLOW9xZjJRCmVWRmR0dzdFZ0lYRUlYUzhLVjFD
            emFwZHp5bGI1ckJjUnR5SCtTRXVWQkEKLS0tIHRPR1l3UkFRT3Z4V2RIR08xTGJz
            YnpGMmxUMjV5NkM4VDRqWk8vQ3EvemsKr3TfyFRfJ4DeaNw4zVNy1/yBO5AP5UNI
            zbrQh6d4q1yzY2CW3GjJekhwP4ePltSzc/R7JPnMBK+jQMlOXN73WQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gmxyeqces6e0t2d5v5lcplm7e4fkw64w4yvfcjz2ca4ee2k43v5smre7z9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdVp4NVo5NVU1cFAzejNn
            Ly9QMzhEbkErWU1rSVdjNkRGUUFpNEt1cEZVCnVVVm9NV3pXQjg0VVVQYWFwYStk
            U2hsUlVUdm5nTGxDWkg3aFFTeFB3NUEKLS0tIFlMbFZUajNmL05LQ011bURPdmpG
            ZG9MM1V1aS9wNnZldDQrOERkRVBrUkEK2Ke30zsISwjHqHvAR1EsY69hLrlSkqKF
            dNX9VZrPMdKf6Wld83T7Tnkl5jtMgNsWEGx+1ZJBqG3RnDfz9eGqWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T23:20:33Z"
    mac: ENC[AES256_GCM,data:XZfSgR3pIvt4EcPD1j4XimDExaov0qNFHMdFcikLdHluBe0BC8JfzyvhAQ7i2kqvkN1zMPU5ZsQHg5KNJs6/6T5cliKRBu4PFvmjf8kuRBjclFytn8Vwx2EAdgBTGSi+5+XR5REM5rParnuQFSNI9lDopmxIJsw8aaV+B3KngHc=,iv:8sN8DG3ESAcVjGEUzo6HltDxo9YhlnauSc0bwptUQss=,tag:6S8BW6RXv2OD55lk8FrLtQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
