cloudflare_api_token: ENC[AES256_GCM,data:9OX7FkfCkSx9j1OXEkPSOMPsGtKLjekkOjKDXNur30KB6VtlnPdWNDp0GwPadeoiQKB8D6I=,iv:s0KEspJDypjYiYdOEANtWnpbDA6KMcMjfYWL3qWESOo=,tag:1WKyarSSIV8EHSXyDO6Xsg==,type:str]
sops:
  age:
    - recipient: age1dsq3jfksmka0gdkxpqpfglyvcusutspj007y4yzsmwfyfyp92yusy7wnlg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMWtlbTlDVVNYUUFRK2F0
        R2h1c2J4QVQyNGk2RkQ1UlJQeVFzRDVIb3o0CnRMWW5CWWVrTnUzd01tMG9tQWRy
        MVZVZXArL0hmV3J0WlcwdWtNWUhHSmcKLS0tIGFqWmdqN1YxWWVsaDhMVlhvbTBp
        WHRwN25odmRGK2YxTE9HZVhSa0FMalkK9S57zQeJF6s1SAhLS5LFQkhAljPXCcQj
        1Bk+m0vearjTQRWJNniHBU06mCQzVZ1WUTdQt2yFBGWCXcdSAwo6ew==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1c3jfx5pxy0ttfxwkwp9cmrclg0en4t04j09342ed622pc5kal9essafrhp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S2paQjhGelJjRm1jenpL
        dHB1WjhWdXhyc2VRelc0ajgvRUwvMGxPRUhzCmZNc0RSS21yTGwwRHB3UkNvbjMx
        a2pDWUovVGxwKzdIcGdMZzlMUVpXTzQKLS0tIFpRYktWcjNXSGUrY3dCTXBSWmF3
        NXdmNWJRTjlSQXZFbFBKaFJBTS9hWEUKhCQ703OLeip7VAECtXGpA7N4B1Y+nmpv
        0AYgIuAHrlm3LZEleijFoj8ypxKHhQFFFuZA0HosSqdPy7zCpC5vTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-16T23:20:33Z"
  mac: ENC[AES256_GCM,data:XZfSgR3pIvt4EcPD1j4XimDExaov0qNFHMdFcikLdHluBe0BC8JfzyvhAQ7i2kqvkN1zMPU5ZsQHg5KNJs6/6T5cliKRBu4PFvmjf8kuRBjclFytn8Vwx2EAdgBTGSi+5+XR5REM5rParnuQFSNI9lDopmxIJsw8aaV+B3KngHc=,iv:8sN8DG3ESAcVjGEUzo6HltDxo9YhlnauSc0bwptUQss=,tag:6S8BW6RXv2OD55lk8FrLtQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
