# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  pkgs,
  ...
}: let
  inherit (lib.godtamnix) enabled;
in {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  godtamnix = {
    hardware = {
      cpu.amd = enabled;

      gpu.nvidia = {
        enable = true;
        open = true;
        powerLimit = 300;
      };
    };
  };

  boot = {
    # This uses the Xanmod kernel, which is a community-maintained kernel that is
    # optimized for throughput, performance, and stability.
    kernelPackages = pkgs.linuxPackages_xanmod_latest;
    kernelParams = [];
    initrd.availableKernelModules = [
      "xhci_pci"
      "ahci"
      "nvme"
      "usb_storage"
      "usbhid"
      "sd_mod"
    ];
    initrd.kernelModules = [
      "xxhash"
      "xxhash_generic"
    ];
    kernelModules = [];
    extraModulePackages = [];
  };
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
