# This is a default home.nix generated by the following home-manager command
#
# home-manager init ./
{
  lib,
  pkgs,
  ...
}: {
  godtamnix = {
    user = {
      enable = true;
      name = "seank";
      fullName = "Sean Khosrowshahi";
      email = lib.godtamnix.decode "c2VhbkBhc3QubGl2ZQ==";
    };

    programs.graphical.browsers = {
      firefox = {
        enable = true;
        # gpuAcceleration = true;
        # hardwareDecoding = true;
        # setDefault = true;
      };
    };

    programs.terminal.ai.opencode = {
      settings = builtins.fromJSON (builtins.readFile ./opencode.json);
      ohMyOpenAgent = builtins.fromJSON (builtins.readFile ./oh-my-openagent.json);
      # ohMyOpenCodeSlim = builtins.fromJSON (builtins.readFile ./oh-my-opencode-slim.json);
    };
  };

  home.packages = with pkgs; [
    fastfetch
    postman
    unzrip
  ];

  programs = {
    claude-code = {
      enable = true;
    };

    git = {
      enable = true;

      settings = {
        push.autoSetupRemote = true;
      };
    };

    fish = {
      enable = true;

      loginShellInit = ''
        set -x NIX_PATH nixpkgs=channel:nixos-unstable
        set -x NIX_LOG info
        set -x TERMINAL kitty
      '';

      interactiveShellInit = ''
        set -x fish_greeting # This sets the greeting to nothing
        fastfetch
      '';
    };

    ssh = {
      enable = true;
      enableDefaultConfig = false;
    };

    starship = {
      enable = true;

      enableFishIntegration = true;
      enableZshIntegration = true;
      enableInteractive = true;

      settings = fromTOML (builtins.readFile ./starship.toml);
    };

    vscode = {
      enable = true;
      extensions = with pkgs.vscode-extensions; [
        catppuccin.catppuccin-vsc
        catppuccin.catppuccin-vsc-icons
        graphql.vscode-graphql
        mkhl.direnv
        redhat.vscode-yaml
        rust-lang.rust-analyzer
        svelte.svelte-vscode
      ];
    };

    yazi = {
      enable = true;
      enableFishIntegration = true;
      shellWrapperName = "y";
    };
  };

  xdg.configFile."Antigravity/Users/settings.json".source = ./antigravity-settings.json;
}
