# This is a default home.nix generated by the following home-manager command
#
# home-manager init ./
{
  lib,
  pkgs,
  ...
}: {
  godtamnix = {
    user = {
      enable = true;
      name = "seank";
      fullName = "Sean Khosrowshahi";
      email = lib.godtamnix.decode "c2VhbkBhc3QubGl2ZQ==";
    };

    programs.graphical.browsers = {
      firefox = {
        enable = true;
        # gpuAcceleration = true;
        # hardwareDecoding = true;
        # setDefault = true;
      };
    };

    programs.terminal.ai.opencode = {
      settings = builtins.fromJSON (builtins.readFile ./opencode.json);
      ohMyOpenAgent = builtins.fromJSON (builtins.readFile ./oh-my-openagent.json);
      # ohMyOpenCodeSlim = builtins.fromJSON (builtins.readFile ./oh-my-opencode-slim.json);
    };
  };

  home.packages = with pkgs; [
    fastfetch
    postman
    unzrip
  ];

  programs = {
    git = {
      enable = true;

      settings = {
        push.autoSetupRemote = true;
      };
    };

    ssh = {
      enable = true;
      enableDefaultConfig = false;

      # matchBlocks = {
      #   "BeastieServerV2" = {
      #     hostname = lib.godtamnix.decode "YmVhc3RpZXNlcnZlcnYyLmdvZHRhbWl0LmNvbQ==";
      #     user = "godtamit";
      #     port = 38888;
      #   };
      # };
    };

    starship = {
      enable = true;

      enableFishIntegration = true;
      enableZshIntegration = true;
      enableInteractive = true;

      settings = fromTOML (builtins.readFile ./starship.toml);
    };

    yazi = {
      enable = true;
      enableFishIntegration = true;
      shellWrapperName = "y";
    };
  };

  xdg.configFile."Antigravity/Users/settings.json".source = ./antigravity-settings.json;
}
